# ==========================================
# Gradle
# ==========================================

org.gradle.jvmargs=-X4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ==========================================
# AndroidX
# ==========================================

android.useAndroidX=true
android.nonTransitiveRClass=true

# ==========================================
# Kotlin
# ==========================================

kotlin.code.style=official
kotlin.incremental=true

# ==========================================
# Build
# ==========================================

android.defaults.buildfeatures.buildconfig=true